---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: diplomado-usach
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: diplomado-usach
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
