---
apiVersion: v1
kind: Service
metadata:
  name: diplomado-usach-svc
  namespace: default
spec:
  ports:
  - name: diplomado-usach-port
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: DevOpsUsach
  type: ClusterIP
